name: cypress_learn_project

on:
  workflow_call:
    inputs:
      job_index:
        type: number
        required: true

env:
  # Set up the Cypress Cloud project ID and record key as environment variables
  # If the Actions secret EXAMPLE_PROJECT_ID is not defined then
  # the projectId is taken from cypress.json (v9) or cypress.config.js (v10 and later).
  # If the Actions secret EXAMPLE_RECORDING_KEY is not defined then recording jobs are skipped.
  GH_ENTERPRISE_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      JOB_INDEX: ${{ inputs.job_index }}
    steps:
      - name: Log runner details
        run: |
          echo '=== Disk information ==='
          df -H
      - name: Allure - Setup Java
        if: always()
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results-${{ env.JOB_INDEX }}
          gh_pages: gh-pages
          allure_report: allure-results-${{ env.JOB_INDEX }}
          allure_history: allure-history-${{ env.JOB_INDEX }}
          keep_reports: 10

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history${{ env.JOB_INDEX }}
