name: cypress_learn_project

on: push

env:
    # Set up the Cypress Cloud project ID and record key as environment variables
    # If the Actions secret EXAMPLE_PROJECT_ID is not defined then
    # the projectId is taken from cypress.json (v9) or cypress.config.js (v10 and later).
    # If the Actions secret EXAMPLE_RECORDING_KEY is not defined then recording jobs are skipped.
    CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6.6.1
        with:
            record: true
            browser: chrome
            

        env: 
            # Get the short ref name of the branch that triggered the workflow run
            COMMIT_INFO_BRANCH: ${{ github.ref_name }}
       