name: cypress_learn_project

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
        fail-fast: false # https://github.com/cypress-io/github-action/issues/48
        matrix:
          containers: [1, 2] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            browser: chrome
            record: true
            parallel: true # Runs test in parallel using settings above
        env:
            # pass GitHub token to allow accurately detecting a build vs a re-run build
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # pass the Cypress Cloud record key as an environment variable
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}