name: cypress_learn_project

on: push

env:
    # Set up the Cypress Cloud project ID and record key as environment variables
    # If the Actions secret EXAMPLE_PROJECT_ID is not defined then
    # the projectId is taken from cypress.json (v9) or cypress.config.js (v10 and later).
    # If the Actions secret EXAMPLE_RECORDING_KEY is not defined then recording jobs are skipped.
    CYPRESS_PROJECT_ID: ${{ secrets.EXAMPLE_PROJECT_ID }}
    CYPRESS_RECORD_KEY: ${{ secrets.EXAMPLE_RECORDING_KEY }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
        fail-fast: false # https://github.com/cypress-io/github-action/issues/48
        matrix:
          containers: [1, 2] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            browser: chrome
            record: true
            parallel: true # Runs test in parallel using settings above
       